# Generated by Django 4.0.3 on 2022-07-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_username_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(default=0, max_length=100, verbose_name='Surname first'),
            preserve_default=False,
        ),
    ]
