# Generated by Django 4.0.3 on 2022-07-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_users_first_name_remove_users_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
    ]
