# Generated by Django 4.0.5 on 2022-07-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='upload image'),
        ),
        migrations.AddField(
            model_name='users',
            name='subscribe',
            field=models.BooleanField(default=True, verbose_name='Subscribe?'),
        ),
        migrations.AlterField(
            model_name='users',
            name='vendor',
            field=models.BooleanField(default=False, verbose_name='Are you a vendor?'),
        ),
    ]
