# Generated by Django 4.0.5 on 2022-07-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_img_users_subscribe_alter_users_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='upload image'),
        ),
    ]
