# Generated by Django 5.0.6 on 2024-07-10 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('thumb', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cart_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='added_product', to='thumb.productwithimage')),
            ],
        ),
    ]
