# Generated by Django 5.1 on 2024-08-29 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bargains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.PositiveIntegerField()),
                ('msg', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ManyToManyField(related_name='bargains_customer+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bargains-product+', to='product.products')),
                ('vendor', models.ManyToManyField(related_name='bargains_vendor+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bargain',
                'verbose_name_plural': 'Bargains',
            },
        ),
    ]
