# Generated by Django 4.0.6 on 2022-07-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
