# Generated by Django 4.0.6 on 2022-07-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusers_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customusers',
            name='merchandise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='phone number'),
        ),
    ]
