# Generated by Django 4.0.6 on 2022-07-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customusers_address_customusers_merchandise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
