services:
  web:
    image: moriire/ecommerce-solutions:ecs_backend
    build: ./ecommerce-solutions
    command: gunicorn ecs.wsgi:application --config gunicorn.py
    volumes:
      - 'static_volume:/home/backend/staticfiles'
      - 'media_volume:/home/backend/mediafiles'
      - './ecommerce-solutions/:/backend'
      - './ecommerce-solutions/logs:/home/backend/logs'
    expose:
      - 8000
    restart: on-failure
    env_file:
      - ./.env/.env.web
    depends_on:
      db:
        condition: service_healthy
  
  frontend_nginx:
    image: moriire/ecommerce-solutions:ecs_frontend_nginx
    ports:
      - 80:80
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    
    depends_on:
      - frontend

  frontend:
    image: moriire/ecommerce-solutions:ecs_frontend
    build: ./frontend
    ports:
      - 3000:80

    volumes:
      - ./frontend:/app
    depends_on:
      - web
    environment:
      - NODE_ENV=production

  nginx_backend:
    build: ./ecommerce-solutions/nginx
    image: moriire/ecommerce-solutions:nginx_backend
    ports:
      - 8000:80
    volumes:
      - 'static_volume:/home/backend/staticfiles'
      - 'media_volume:/home/backend/mediafiles'
      
    depends_on:
      - web
   
  db:
    image: moriire/ecommerce-solutions/ecs_database
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "ecs" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env/.env.db
    ports:
      - "5432:5432"
    volumes:
      - 'db_data:/var/lib/postgresql/data/'

  redis:
    image: moriire/ecommerce-solutions/redis
    
volumes:
  db_data:
  static_volume:
  media_volume: