services:
  web:
    container_name: ecs_backend
    build: ./ecommerce-solutions
    command: gunicorn ecs.wsgi:application --config gunicorn.py
    volumes:
      - 'static_volume:/home/backend/staticfiles'
      - 'media_volume:/home/backend/mediafiles'
      - './ecommerce-solutions/:/backend'
      - './ecommerce-solutions/logs:/home/backend/logs'
    expose:
      - 8000
    restart: on-failure

    environment:
      - DEBUG
      - CONN_MAX_AGE
      - SECRET_KEY
      - DJANGO_SETTINGS_MODULE
      - DJANGO_ALLOWED_HOSTS
      - DJANGO_SUPERUSERNAME
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POOL_MIN_SIZE
      - POOL_MAX_SIZE
      - POOL_TIMEOUT
      - SQL_ENGINE
      - SQL_DATABASE
      - SQL_USER
      - SQL_PASSWORD
      - SQL_HOST
      - SQL_PORT
      - DATABASE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_S3_SIGNATURE_VERSION
      - AWS_S3_REGION_NAME
      - STATIC_LOCATION
      - AWS_S3_FILE_OVERWRITE
      - AWS_LOCATION
      - AWS_S3_VERIFY
      - EMAIL_USE_TLS
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_PORT
      - DEFAULT_FROM_EMAIL

    depends_on:
      db:
        condition: service_healthy
    
  frontend_nginx:
    container_name: ecs_frontend_nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    
    depends_on:
      - frontend

  frontend:
    container_name: ecs_frontend
    build: ./frontend
    ports:
      - 3000:80

    volumes:
      - ./frontend:/app
    depends_on:
      - web
    environment:
      - NODE_ENV=production
      - BACKEND_API_ENDPOINT=http://127.0.0.1/api/
      

  nginx_backend:
    build: ./ecommerce-solutions/nginx
    container_name: nginx_backend
    ports:
      - 8000:80
    volumes:
      - 'static_volume:/home/backend/staticfiles'
      - 'media_volume:/home/backend/mediafiles'
      
    depends_on:
      - web 
  db:
    container_name: ecs_database
    image: postgres:16.0-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "ecs" ]
      interval: 5s
      timeout: 5s
      retries: 5
    
    ports:
      - "5432:5432"
    volumes:
      - 'db_data:/var/lib/postgresql/data/'

  redis:
    image: "redis:alpine"
    

volumes:
  db_data:
  static_volume:
  media_volume: