services:
  web:
    build: ./ecommerce-solutions
    command: gunicorn ecs.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.web
    depends_on:
      - db

  frontend:
    image: nginx:1.25
    build: ./frontend
    container_name: frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web

  db:
    image: postgres:15
    env_file:
      - ./.env.db
    volumes:
      - db_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/backend/staticfiles
      - media_volume:/home/backend/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  db_data:
  static_volume:
  media_volume: