services:
  web:
    build: ./ecommerce-solutions
    command: gunicorn ecs.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.web
    depends_on:
      - db
  db:
    image: postgres:15
    env_file:
      - ./.env.db
    volumes:
      - db_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  db_data:
  static_volume:
  media_volume: