# Generated by Django 5.0.6 on 2024-06-22 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('sub_data', models.JSONField(editable=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash-package+', to='packages.packages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash-user+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'flash Sale',
                'verbose_name_plural': 'Flash Sales',
            },
        ),
    ]
