# Generated by Django 4.0.6 on 2022-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
