# Generated by Django 5.1 on 2024-08-29 10:45

import django.db.models.deletion
import thumb.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=thumb.models.product_image_path, verbose_name='Upload Image')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductWithImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=8)),
                ('images', models.ManyToManyField(blank=True, related_name='product_images', to='thumb.productimage')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_product', to='product.products')),
            ],
        ),
    ]
