# Generated by Django 5.0.6 on 2024-07-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwithimage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
