# Generated by Django 5.0.6 on 2024-06-24 21:47

import django.db.models.deletion
import thumbs.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_thumbs'),
        ('thumbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=thumbs.models.product_image_path, verbose_name='Upload Image')),
                ('caption', models.CharField(max_length=6)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductWithImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ManyToManyField(blank=True, related_name='product_images', to='thumbs.productimage')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_product', to='products.products')),
            ],
        ),
        migrations.DeleteModel(
            name='Thumbs',
        ),
    ]
