# Generated by Django 5.0.6 on 2024-07-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumb', '0002_productwithimage_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwithimage',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='productwithimage',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='pending', max_length=8),
            preserve_default=False,
        ),
    ]
