# Generated by Django 5.1 on 2024-08-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumb', '0004_alter_productwithimage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productwithimage',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=8),
        ),
    ]
