# Generated by Django 4.0.6 on 2022-09-24 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('img', models.ImageField(blank=True, null=True, upload_to='store/banner', verbose_name='upload image')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('store_slug', models.SlugField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('merchandise', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('viewed_by', models.ManyToManyField(blank=True, null=True, related_name='profile_viewed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
