# Generated by Django 4.0.6 on 2022-09-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='store_name',
            field=models.CharField(default='', editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
