# Generated by Django 4.0.6 on 2022-08-26 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='products')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(default=0)),
                ('caption', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_thumb', to='products.products')),
            ],
        ),
    ]
