# Generated by Django 4.0.6 on 2022-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bargains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.PositiveIntegerField()),
                ('msg', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bargain',
                'verbose_name_plural': 'Bargains',
            },
        ),
    ]
