# Generated by Django 4.0.6 on 2022-08-26 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bargains', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bargains',
            name='customer',
            field=models.ManyToManyField(related_name='bargains_customer+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bargains',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bargains-product+', to='products.products'),
        ),
        migrations.AddField(
            model_name='bargains',
            name='vendor',
            field=models.ManyToManyField(related_name='bargains_vendor+', to=settings.AUTH_USER_MODEL),
        ),
    ]
