# Generated by Django 4.0.3 on 2022-07-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_vendor'),
        ('thumb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_thumb', to='product.product'),
        ),
    ]
