# Generated by Django 4.0.5 on 2022-07-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thumb', '0002_alter_thumb_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumb',
            name='img',
            field=models.ImageField(upload_to='products'),
        ),
    ]
