# Generated by Django 4.0.6 on 2022-07-10 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Super'), (3, 'Mega'), (4, 'Jumbo')])),
                ('enabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash-product+', to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash-user+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'flash Sale',
                'verbose_name_plural': 'Flash Sales',
            },
        ),
    ]
