# Generated by Django 4.0.6 on 2022-07-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Super'), (3, 'Mega'), (4, 'Jumbo')])),
                ('enabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'flash Sale',
                'verbose_name_plural': 'Flash Sales',
            },
        ),
    ]
