# Generated by Django 4.0.6 on 2022-08-01 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        ('flash', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flash',
            name='product',
        ),
        migrations.AlterField(
            model_name='flash',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash-package+', to='packages.packages'),
        ),
    ]
