# Generated by Django 4.0.5 on 2022-07-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_product_vendor'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.IntegerField(choices=[('Normal', 1), ('Super', 2), ('Mega', 3), ('Jumbo', 4)])),
                ('enabled', models.BooleanField()),
                ('clicks', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash-product+', to='product.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash-vendor+', to='vendor.vendor')),
            ],
            options={
                'verbose_name': 'flash Sale',
                'verbose_name_plural': 'flash Sales',
            },
        ),
    ]
