# Generated by Django 4.0.5 on 2022-07-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='package',
            field=models.CharField(choices=[('Normal', 1), ('Super', 2), ('Mega', 3), ('Jumbo', 4)], max_length=15),
        ),
    ]
