# Generated by Django 4.0.5 on 2022-07-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_alter_flash_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='package',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Super'), (3, 'Mega'), (4, 'Jumbo')]),
        ),
    ]
