# Generated by Django 4.0.6 on 2022-09-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('amount', models.PositiveIntegerField()),
                ('interval', models.CharField(choices=[('annually', 'Annually'), ('biannually', 'Biannually'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily')], max_length=15)),
                ('plan_code', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_data', models.JSONField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
