# Generated by Django 4.0.6 on 2022-09-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='plan_data',
        ),
        migrations.AddField(
            model_name='packages',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='plan_code',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
