# Generated by Django 4.0.3 on 2022-06-28 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
