# Generated by Django 5.0.6 on 2024-07-06 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(blank=True, to='product.products')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wish_user', to='profile.profile')),
            ],
        ),
    ]
