"""
Django settings for ecs project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c+=02zv07*647ejmnqjn7+t=rbvl6j_mv9=k9dqye=7n==$o=s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["www.megadey.org", "megadey.org", "ecs.pythonanywhere.com", "127.0.0.1", "localhost" ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "storages",
    "rest_framework",
    'knox',
    'rest_framework.authtoken',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    "users",
    #"profiles",
    "products",
    "thumbs",
    "packages",
    "flash",
    "bargains",
    "payment",
    'coreapi', # Coreapi for coreapi documentation
    'drf_yasg', # drf_yasg fro Swagger documentatio
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / "templates/", ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    #'default': {
    #    'ENGINE': 'django.db.backends.mysql',
     #   'NAME': 'ecs$ecsolutions',
      #  'USERNAME': 'ecs',
       # 'HOST': 'ecs.mysql.pythonanywhere-services.com',
        #'PASSWORD': '',
    #}

    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ( 'dj_rest_auth.jwt_auth.JWTCookieAuthentication',),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'mega-auth'
JWT_AUTH_REFRESH_COOKIE = 'mega-refresh-token'

REST_AUTH_REGISTER_SERIALIZERS = {                            
    'REGISTER_SERIALIZER': 'users.models.RegisterSerializer',
}
ACCOUNT_ADAPTER = 'users.forms.NewAllauthAdapter'
AUTH_USER_MODEL = "users.CustomUsers"
SITE_ID = 4
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USER_MODEL_USERNAME_FIELD=None
ACCOUNT_EMAIL_VERIFICATION = 'none'#mandatory
ACCOUNT_USERNAME_REQUIRED = False
# Additional configuration settings
SOCIALACCOUNT_QUERY_EMAIL = True
#ACCOUNT_LOGOUT_ON_GET= True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ]
    },
    'facebook': {
        'SCOPE': [
            'public_profile',
            'email',
        ],
        'FIELDS': [
            'id',
            'email',
            'name',
            'first_name',
            'last_name',
            'verified',
            'locale',
            'timezone',
            'link',
            'gender',
            'updated_time',
        ],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
    }
}
#ACCOUNT_SIGNUP_FORM_CLASS='users.forms.SocialPasswordedSignupForm'
SOCIALACCOUNT_FORMS = {
    'signup': 'users.forms.SocialPasswordedSignupForm'
}
ACCOUNT_FORMS = {
    'signup': 'users.forms.SocialPasswordedSignupForm'
}
# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = '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'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = "mail@megadey.org"

ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = 'email-success'  # if you are not logged in

ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/'  # if you are logged in

UNIQUE_EMAIL = True  # just to be sure, ok
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'static')
#, "/home/ecs/ecommerce-solutions/static/" 
]

STATIC_URL = '/static/'

#STATIC_ROOT="/static/"
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ORIGIN_ALLOW_ALL = not False
CORS_ALLOWED_ORIGINS = [
    "https://www.megadey.org",
    "http://127.0.0.1:8080",
    "http://localhost:8080",
    #"*",
]

Env = os.environ

AWS_ACCESS_KEY_ID = "AKIA6PO6FQSVJMLA7F6E"
AWS_SECRET_ACCESS_KEY = "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"
AWS_STORAGE_BUCKET_NAME = "megadey"
AWS_S3_SIGNATURE_VERSION = 's3v4'
#AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
# s3 static settings
#AWS_LOCATION = 'static'
AWS_S3_REGION_NAME = "us-east-1"
#STATIC_LOCATION = 'static'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_VERIFY = True

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

#CSRF_TRUSTED_ORIGINS = ["megadey.org", "*"]


