# Generated by Django 5.0.6 on 2024-07-02 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('country', models.CharField(default='Nigeria', max_length=24, verbose_name='Country')),
                ('address_1', models.CharField(max_length=128, verbose_name='Address 1')),
                ('address_2', models.CharField(max_length=128, verbose_name='Address 2')),
                ('zip_code', models.CharField(max_length=8, verbose_name='Zip Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_address', to='profiles.profile')),
            ],
        ),
    ]
