# Generated by Django 5.0.6 on 2024-07-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='address_1',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='address_2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Zip Code'),
        ),
    ]
