# Generated by Django 5.1 on 2024-08-20 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_locationpricemodel_alter_shipping_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationpricemodel',
            options={'verbose_name': 'Product Shipping', 'verbose_name_plural': 'Shipping Informations'},
        ),
        migrations.AlterField(
            model_name='shipping',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
