# Generated by Django 5.1 on 2024-08-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_alter_locationpricemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_city', to='shipping.locationpricemodel'),
        ),
    ]
