# Generated by Django 5.1 on 2024-08-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0004_alter_shipping_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Zip Code'),
        ),
    ]
