# Generated by Django 5.1 on 2024-08-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0005_shipping_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Phone'),
        ),
    ]
