# Generated by Django 5.0.6 on 2024-06-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs', '0002_productimage_productwithimage_delete_thumbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='caption',
        ),
    ]
