# Generated by Django 5.0.6 on 2024-06-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='thumbs',
        ),
    ]
