# Generated by Django 5.0 on 2024-07-02 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='store/banner', verbose_name='upload image')),
                ('store_name', models.CharField(max_length=100, unique=True)),
                ('store_slug', models.SlugField(editable=False, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('merchandise', models.TextField(blank=True, null=True)),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('viewed_by', models.ManyToManyField(blank=True, related_name='profile_viewed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
