# Generated by Django 5.0.6 on 2024-08-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_locationpricing_profile_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='location',
        ),
    ]
