# Generated by Django 4.0.3 on 2022-07-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
