# Generated by Django 4.0.5 on 2022-07-01 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flash', '0003_alter_flash_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto', models.BooleanField(default=False)),
                ('reference' models.CharField(max_length=100)),
                ('auth_code', models.CharField(max_length=128)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('flash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_pay+', to='flash.flash')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_by+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
