# Generated by Django 4.0.3 on 2022-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
