# Generated by Django 5.1 on 2024-08-29 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('shipping', '__first__'),
        ('thumb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(blank=True, max_length=16, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=12, null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('completed', 'Completed')], default='UNPAID', max_length=9)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('carts', models.ManyToManyField(blank=True, to='cart.cart')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_by', to=settings.AUTH_USER_MODEL)),
                ('shipping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping', to='shipping.shipping')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_product', to='thumb.productwithimage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorder_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
