# Generated by Django 5.0.6 on 2024-08-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_count'),
        ('order', '0002_alter_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='carts',
            field=models.ManyToManyField(blank=True, to='cart.cart'),
        ),
    ]
