# Generated by Django 5.1 on 2024-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_shipping_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
