# Generated by Django 5.0.6 on 2024-07-17 15:18

import product.models.category
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.category.category_image_path),
        ),
    ]
