# Generated by Django 5.0.6 on 2024-07-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='thumb',
            new_name='img',
        ),
    ]
