# Generated by Django 5.0.6 on 2024-08-06 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_thumb_category_img'),
        ('profile', '0003_rename_state_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='profile.profile'),
        ),
    ]
