# Generated by Django 5.1 on 2024-08-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='store_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Store Name'),
            preserve_default=False,
        ),
    ]
