# Generated by Django 4.2.13 on 2024-06-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='username',
            field=models.CharField(default='Mobolaji', max_length=8, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customusers',
            name='phone',
            field=models.CharField(max_length=8, unique=True, verbose_name='phone number'),
        ),
    ]
