# Generated by Django 5.1 on 2024-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusers_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='store_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Store Name'),
        ),
    ]
