# Generated by Django 4.2.13 on 2024-06-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusers_username_alter_customusers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='username',
            field=models.CharField(max_length=8, unique=True, verbose_name='Username'),
        ),
    ]
