# Generated by Django 4.2.13 on 2024-06-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customusers_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='username',
            field=models.CharField(max_length=12, unique=True, verbose_name='Username'),
        ),
    ]
