# Generated by Django 4.0.6 on 2022-09-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_packages_interval_remove_packages_plan_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='interval',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
