# Generated by Django 4.0.6 on 2022-09-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packages_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packages',
            name='name',
            field=models.CharField(default='free', max_length=40),
        ),
        migrations.AlterField(
            model_name='packages',
            name='plan_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
