# Generated by Django 4.0.6 on 2022-09-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='thumbs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_thumbs', to='thumbs.thumbs'),
        ),
    ]
