# Generated by Django 4.0.6 on 2022-07-11 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='viewed_by',
            field=models.ManyToManyField(related_name='viewed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
