# Generated by Django 4.0.6 on 2022-09-16 21:40

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('thumbs', '0001_initial'),
        ('products', '0002_alter_products_thumbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='thumbs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.Empty, related_name='products_thumbs', to='thumbs.thumbs'),
        ),
    ]
